version: '3.9'

services:
  kroma-geth:
    container_name: kroma-geth
    image: kromanetwork/geth:${IMAGE_TAG__KROMA_GETH}
    restart: unless-stopped
    env_file:
      - envs/${NETWORK_NAME}/geth.env
    entrypoint:
      - /bin/sh
      - /.kroma/entrypoint.sh
    ports:
      - 6060:6060
      - 8545:8545
      - 8546:8546
      - 8551:8551
      - 30304:30304/tcp
      - 30303:30303/udp
    volumes:
      - db:/.kroma/db
      - ./keys/jwt-secret.txt:/.kroma/keys/jwt-secret.txt
      - ./config/${NETWORK_NAME}/genesis.json:/.kroma/config/genesis.json
      - ./scripts/entrypoint.sh:/.kroma/entrypoint.sh
    profiles:
      - fullnode
      - validator

  kroma-node:
    depends_on:
      - kroma-geth
    container_name: kroma-node
    image: kromanetwork/node:${IMAGE_TAG__KROMA_NODE}
    restart: unless-stopped
    env_file:
      - envs/${NETWORK_NAME}/node.env
    ports:
      - 9545:8545
      - 7300:7300
      - 9003:9003/tcp
      - 9003:9003/udp
    volumes:
      - ./keys/p2p-node-key.txt:/.kroma/keys/p2p-node-key.txt
      - ./keys/jwt-secret.txt:/.kroma/keys/jwt-secret.txt
      - ./config/${NETWORK_NAME}/rollup.json:/.kroma/config/rollup.json
      - ./logs:/.kroma/logs
    profiles:
      - fullnode
      - validator

  kroma-validator:
    depends_on:
      - kroma-node
    container_name: kroma-validator
    image: kromanetwork/validator:${IMAGE_TAG__KROMA_VALIDATOR}
    restart: unless-stopped
    env_file:
      - envs/${NETWORK_NAME}/validator.env
    profiles:
      - validator

volumes:
  db:
