version: '3.9'

services:
  kroma-geth:
    container_name: kroma-geth
    image: kromanetwork/geth:${IMAGE_TAG__KROMA_GETH}
    restart: unless-stopped
    stop_grace_period: 50s
    env_file:
      - envs/${NETWORK_NAME}/geth.env
    entrypoint:
      - /bin/sh
      - /.kroma/entrypoint.sh
    ports:
      - 6060:6060
      - 8545:8545
      - 8546:8546
      - 8551:8551
      - 30304:30304/tcp
      - 30303:30303/udp
    volumes:
      - db-${NETWORK_NAME}:/.kroma/db
      - ./keys/jwt-secret.txt:/.kroma/keys/jwt-secret.txt
      - ./config/${NETWORK_NAME}/genesis.json:/.kroma/config/genesis.json
      - ./scripts/entrypoint.sh:/.kroma/entrypoint.sh
    profiles:
      - fullnode
      - validator
      - validator+proxy

  kroma-node:
    depends_on:
      - kroma-geth
    container_name: kroma-node
    image: kromanetwork/node:${IMAGE_TAG__KROMA_NODE}
    restart: unless-stopped
    stop_grace_period: 50s
    env_file:
      - envs/${NETWORK_NAME}/node.env
    ports:
      - 9545:8545
      - 7300:7300
      - 9003:9003/tcp
      - 9003:9003/udp
    volumes:
      - ./keys/p2p-node-key.txt:/.kroma/keys/p2p-node-key.txt
      - ./keys/jwt-secret.txt:/.kroma/keys/jwt-secret.txt
      - ./config/${NETWORK_NAME}/rollup.json:/.kroma/config/rollup.json
    profiles:
      - fullnode
      - validator
      - validator+proxy

  kroma-validator:
    depends_on:
      - kroma-node
    container_name: kroma-validator
    image: kromanetwork/validator:${IMAGE_TAG__KROMA_VALIDATOR}
    restart: unless-stopped
    stop_grace_period: 50s
    env_file:
      - envs/${NETWORK_NAME}/validator.env
    profiles:
      - validator
      - validator+proxy

  kroma-prover-proxy:
    container_name: kroma-prover-proxy
    image: kromanetwork/prover-proxy:${IMAGE_TAG__KROMA_PROVER_PROXY}
    restart: unless-stopped
    stop_grace_period: 50s
    env_file:
      - envs/${NETWORK_NAME}/prover-proxy.env
    volumes:
      - db-${NETWORK_NAME}:/.prover/proofs
    profiles:
      - validator+proxy

  # Because kroma-prover requires a lot of resources,
  # It is recommended to run it on a different server rather than on the same server.
  kroma-prover:
    container_name: kroma-prover
    image: kromanetwork/prover:${IMAGE_TAG__KROMA_PROVER}
    restart: unless-stopped
    stop_grace_period: 50s
    env_file:
      - envs/${NETWORK_NAME}/prover.env
    volumes:
      - db-${NETWORK_NAME}:/app/out_proof
    profiles:
      - prover

volumes:
  db-mainnet:
  db-sepolia:
